# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b6ca6bea7e59fef09b8c194072ac8c83de6eff6cc9bb7ed26e9d8df5d285ea1b3736dc34a42e3b2bcf24b92f24da4d70dbb7d11bd47c1a9b16a5fd0e90227d53

test:
  secret_key_base: 417710db59e0370a37b3dfc40930bbe1b003b7131d4ea937132b72cab10ac7e6ab5e550228770928dcfbd845a36ace44cfa0a3055724a48328923e2364869399

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
